@echo off

REM ===============================================
REM Script: SetContentDockerImage.bat
REM Description: Prepare the deployment package by copying the required files to the 'deploy' directory 
REM and then transferring those files to the remote server using SCP.
REM ===============================================

REM ==============================
REM Parameters
REM ==============================

SET PipelinePath=%1
SET ApplicationPath=%2
SET SSHPrivateKeyPath=%3
SET SSHUser=%4
SET SSHHost=%5
SET RepositoryPath=%6

REM ==============================
REM Script
REM ==============================

REM Checks if the 'deploy' folder doesn't exist, and if it does, creates it.
IF NOT exist %PipelinePath%\deploy (  
    mkdir %PipelinePath%\deploy && echo created
)

REM Copies the 'src' folder generated by the build into the 'deploy' folder.
xcopy %ApplicationPath%\src %PipelinePath%\deploy\src /E /H /C /I /Y

REM Copies the 'angular.json' file into the 'deploy' folder.
xcopy %ApplicationPath%\angular.json %PipelinePath%\deploy /Y

REM Copies the 'package.json' file into the 'deploy' folder.
xcopy %ApplicationPath%\package.json %PipelinePath%\deploy /Y

REM Copies the 'package-lock.json' file into the 'deploy' folder.
xcopy %ApplicationPath%\package-lock.json %PipelinePath%\deploy /Y

REM Copies the 'tsconfig.app.json' file into the 'deploy' folder.
xcopy %ApplicationPath%\tsconfig.app.json %PipelinePath%\deploy /Y

REM Copies the 'tsconfig.json' file into the 'deploy' folder.
xcopy %ApplicationPath%\tsconfig.json %PipelinePath%\deploy /Y

REM Copies the 'tsconfig.spec.json' file into the 'deploy' folder.
xcopy %ApplicationPath%\tsconfig.spec.json %PipelinePath%\deploy /Y

REM Copies the content of the 'docker' folder into the 'deploy' folder.
xcopy %PipelinePath%\docker\* %PipelinePath%\deploy /E /H /C /I /Y

REM Copies the 'sh' folder into the 'deploy' folder.
xcopy %PipelinePath%\sh %PipelinePath%\deploy\sh /E /H /C /I /Y

REM ============================
REM DELETE FILES ON THE REMOTE SERVER
REM ============================
ssh -i %SSHPrivateKeyPath% %SSHUser%@%SSHHost% "rm -rf %RepositoryPath%/*"

REM ============================
REM RECURSIVE COPY OF DEPLOY FOLDER TO REMOTE SERVER
REM ============================
scp -r -i %SSHPrivateKeyPath% %PipelinePath%\deploy\* %SSHUser%@%SSHHost%:%RepositoryPath%
