@echo off
REM ==============================================================================
REM Description: Prepara el paquete de despliegue copiando los archivos
REM   requeridos al directorio 'deploy' y transfiriendolos al servidor remoto
REM   via SCP, con SSH endurecido y validacion temprana de argumentos.
REM Author: Pipeline_Jenkins_Angular_Docker maintainers
REM Usage: SetContentDockerImage.bat ^<PipelinePath^> ^<ApplicationPath^> ^<SSHPrivateKeyPath^> ^<SSHUser^> ^<SSHHost^> ^<RepositoryPath^>
REM Env Vars: ninguna (todo por argumentos).
REM Dependencies: xcopy, mkdir, ssh, scp (OpenSSH)
REM Exit codes: 0 ok; 2 uso/argumentos invalidos.
REM ==============================================================================
setlocal EnableExtensions

if "%~1"=="" echo Usage: SetContentDockerImage.bat ^<PipelinePath^> ^<ApplicationPath^> ^<SSHPrivateKeyPath^> ^<SSHUser^> ^<SSHHost^> ^<RepositoryPath^> 1>&2 & exit /b 2
if "%~2"=="" echo Usage: SetContentDockerImage.bat ^<PipelinePath^> ^<ApplicationPath^> ^<SSHPrivateKeyPath^> ^<SSHUser^> ^<SSHHost^> ^<RepositoryPath^> 1>&2 & exit /b 2
if "%~3"=="" echo Usage: SetContentDockerImage.bat ^<PipelinePath^> ^<ApplicationPath^> ^<SSHPrivateKeyPath^> ^<SSHUser^> ^<SSHHost^> ^<RepositoryPath^> 1>&2 & exit /b 2
if "%~4"=="" echo Usage: SetContentDockerImage.bat ^<PipelinePath^> ^<ApplicationPath^> ^<SSHPrivateKeyPath^> ^<SSHUser^> ^<SSHHost^> ^<RepositoryPath^> 1>&2 & exit /b 2
if "%~5"=="" echo Usage: SetContentDockerImage.bat ^<PipelinePath^> ^<ApplicationPath^> ^<SSHPrivateKeyPath^> ^<SSHUser^> ^<SSHHost^> ^<RepositoryPath^> 1>&2 & exit /b 2
if "%~6"=="" echo Usage: SetContentDockerImage.bat ^<PipelinePath^> ^<ApplicationPath^> ^<SSHPrivateKeyPath^> ^<SSHUser^> ^<SSHHost^> ^<RepositoryPath^> 1>&2 & exit /b 2

SET PipelinePath=%1
SET ApplicationPath=%2
SET SSHPrivateKeyPath=%3
SET SSHUser=%4
SET SSHHost=%5
SET RepositoryPath=%6

REM ==============================
REM Script
REM ==============================

echo [%DATE% %TIME%] Preparing deploy package in %PipelinePath%\deploy
REM Creates the 'deploy' folder if it does not exist.
IF NOT exist "%PipelinePath%\deploy" (
    mkdir "%PipelinePath%\deploy"
)

REM Copies the 'src' folder generated by the build into the 'deploy' folder.
xcopy "%ApplicationPath%\src" "%PipelinePath%\deploy\src" /E /H /C /I /Y

REM Copies the root config files into the 'deploy' folder.
xcopy "%ApplicationPath%\angular.json" "%PipelinePath%\deploy\" /Y
xcopy "%ApplicationPath%\package.json" "%PipelinePath%\deploy\" /Y
xcopy "%ApplicationPath%\package-lock.json" "%PipelinePath%\deploy\" /Y
xcopy "%ApplicationPath%\tsconfig.app.json" "%PipelinePath%\deploy\" /Y
xcopy "%ApplicationPath%\tsconfig.json" "%PipelinePath%\deploy\" /Y
xcopy "%ApplicationPath%\tsconfig.spec.json" "%PipelinePath%\deploy\" /Y

REM Copies the content of the 'docker' folder into the 'deploy' folder.
xcopy "%PipelinePath%\docker\*" "%PipelinePath%\deploy\" /E /H /C /I /Y

REM Copies the 'sh' folder into the 'deploy' folder.
xcopy "%PipelinePath%\sh" "%PipelinePath%\deploy\sh\" /E /H /C /I /Y

REM ============================
REM DELETE FILES ON THE REMOTE SERVER (guarded: never rm empty or root path)
REM ============================
if not "%RepositoryPath%"=="" if not "%RepositoryPath%"=="/" ssh -o StrictHostKeyChecking=yes -o BatchMode=yes -i %SSHPrivateKeyPath% %SSHUser%@%SSHHost% "[ -n '%RepositoryPath%' ] && [ '%RepositoryPath%' != '/' ] && rm -rf -- '%RepositoryPath%/*'"

REM ============================
REM RECURSIVE COPY OF DEPLOY FOLDER TO REMOTE SERVER
REM ============================
scp -r -o StrictHostKeyChecking=yes -o BatchMode=yes -i %SSHPrivateKeyPath% "%PipelinePath%\deploy\*" %SSHUser%@%SSHHost%:%RepositoryPath%

echo [%DATE% %TIME%] Deploy package transferred to %SSHUser%@%SSHHost%:%RepositoryPath%
